spring.datasource.url=jdbc:postgresql://ep-round-water-aidq2itn.c-4.us-east-1.aws.neon.tech/PortfolioView?sslmode=require
spring.datasource.username=portfolio_view_admin
spring.datasource.password=#PortfolioView021
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=8080

# JWT Configuration
jwt.secret=R0s9x4XzzWAH4B7M4Dx8xc5piJCmrwoYRtzLHQ9bOo0=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=2592000000

# HikariCP Connection Pool settings
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# Encryption Key for Database Fields
app.encryption.secret-key=PortfolioViewSecretKey2026!@#$

# High-Concurrency Throughput
spring.threads.virtual.enabled=true
